version: "3.8"

services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:7
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:7
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
    - mongo3_data:/data/db

  mongo4:
    image: mongo:7
    container_name: mongo4
    ports:
      - "27020:27017"
    volumes:
      - mongo4_data:/data/db
    profiles:
      - expansion
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes  # persist cache across restarts

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    platform: linux/amd64
    environment:
      - CLUSTER_NAME=distrib_db
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    profiles:
      - hdfs

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    platform: linux/amd64
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_address=0.0.0.0:9866
      - HDFS_CONF_dfs_datanode_http_address=0.0.0.0:9864
      - HDFS_CONF_dfs_datanode_hostname=localhost   
    ports:
      - "9864:9864"
      - "9866:9866"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    profiles:
      - hdfs
    depends_on:
      - namenode

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo4_data:
  redis_data:
  hadoop_namenode:    
  hadoop_datanode:   
